import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/header/page";

export const metadata: Metadata = {
  title: "newWorld",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
